name: checkov-terraform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  TERRAFORM_DIRECTORY: './src'

jobs:
  checkov-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar o Checkov via pip
        run: |
          pip install checkov

      - name: Instalar o Checkov via pip
        run: |
          checkov
          checkov --help

      - name: Instalar o Checkov via pip
        run: |
          checkov
          checkov --help

      - name: Criar diretorio /results para armazenar os resultados gerados com o Checkov
        run: |
          mkdir results
  
      - name: Executar analise com o Checkov
        run: |
          checkov -d ${{ env.TERRAFORM_DIRECTORY }} -o cli -o markdown --output-file-path ./results

      - name: Exibir arquivos gerados apos execucao do Checkov em /results
        run: |
          cd results
          ls
        if: always()

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./results_sarif.sarif
          category: checkov-terraform
        if: always()
