name: checkov-terraform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  TERRAFORM_DIRECTORY: './src'
  RESULTS_TERRAFORM_ANALYSIS: './results/results-azure-terraform.sarif'

jobs:
  checkov-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar o Checkov via pip
        run: |
          pip install checkov

      - name: Instalar o Checkov via pip
        run: |
          checkov
          checkov --help

      - name: Executar analise com o Checkov
        run: |
          checkov -d ${{ env.TERRAFORM_DIRECTORY }} -o cli -o sarif --output-file-path ./results-azure-terraform.sarif

      - name: Exibir arquivos gerados apos execucao do Checkov
        run: |
          ls
        if: always()

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./results-azure-terraform.sarif
          category: checkov-terraform
        if: always()
